### ISSUE TITLE
[Fantia] This user isn't being reported being on Kemono when they are

### ISSUE THREAD

**Issue by NatsuNiNi** [mbahArip/KemonoButton#10]
This user isn't being reported as part of kemono:
https://fantia.jp/fanclubs/380286

But they are on kemono:
https://kemono.su/fantia/user/380286

Btw, I tried to import fantia key, but log shows Status: In Progress Total: 0 for days

**Comment by mbahArip** [comment]
My bad! It's because I'm using the fanclub name as the keyword, that's why it's show as not found.
I'll fix it as soon as possible.

You can ask about the fantia key problem to their chan / telegram / contact page, since this project is my personal project and not affiliated with kemono/coomer

**Comment by NatsuNiNi** [comment]
Thank you for your reply and active handling! 

I mistakenly thought that this was also the official branch of kemono XD

**Comment by mbahArip** [comment]
No problem haha

Btw, I'll reopen this one so it shows up on my to-do list.

**Comment by mbahArip** [comment]
Fixed on v2.0.4
![image](https://github.com/mbahArip/KemonoButton/assets/62494292/dd500b54-036b-4c32-87c0-e0e3e73a832e)

Now it should be searching using UID instead of username
If your script not automatically updating, please reinstall using the link on the README
