### ISSUE TITLE
patreon does not work 

### ISSUE THREAD

**Issue by timeg7100** [mbahArip/KemonoButton#3]
**Describe the bug**
patreon does not work

**To Reproduce**
1. Go to 'patreon'
2. nothing appears

**Expected behavior**
the button does not appear

**Comment by mbahArip** [comment]
Implemented.
Please update the script to 1.0.7

![image](https://github.com/mbahArip/KemonoButton/assets/62494292/b7914919-4f9c-4637-86da-c752a39cd47a)
![image](https://github.com/mbahArip/KemonoButton/assets/62494292/995df2ca-d272-4592-b261-e2afc0b1a44c)
