### ISSUE TITLE
patreon bugged

### ISSUE THREAD

**Issue by TyreneLindstar** [mbahArip/KemonoButton#4]
**Describe the bug**
kemono profile not found, but it's there on kemono

Profile not found.

 - OS: [e.g. Windows 10]
 - Browser [e.g. chrome]
 - Version [e.g. latest]

**Comment by mbahArip** [comment]
Fixed on 1.1.3.
You can update it by clicking on last update on tampermonkey dashboard or click the install link on Readme file.
(It might be broken again if they updated the layout, but let's hope it wont ;-;)

![image](https://github.com/mbahArip/KemonoButton/assets/62494292/e85ed4de-e43b-4b34-9c47-1906c57e7e7d)
