### ISSUE TITLE
[Fanbox] This user isn't being reported being on Kemono when they are

### ISSUE THREAD

**Issue by Linden10** [mbahArip/KemonoButton#8]
This user isn't being reported as part of kemono:
https://www.fanbox.cc/@at-nya5

But they are on kemono:
https://kemono.su/fanbox/user/75618515

That's all.

**Comment by mbahArip** [comment]
It should be fixed now.
Make sure the script version is `2.0.3/fanbox-fix`, in case you're still on `2.0.2` please reinstall the script

![image](https://github.com/mbahArip/KemonoButton/assets/62494292/b3a2aa49-be35-47f6-af86-df24c8a5c9fe)

**Comment by Linden10** [comment]
It works! Thank you!
